---
image: Ubuntu2004
stack: jdk 15
init:
  - sudo apt-get update
  - sudo apt-get install -y fakeroot
build_script:
  - ./gradlew build
  - ls -l ./build/jpackage
artifacts:
  - name: debfile
    path: 'build\jpackage\*.deb'
  - name: rpmfile
    path: 'build\jpackage\*.rpm'
  - name: pkgfile
    path: 'build\jpackage\*.pkg'
  - name: exefile
    path: 'build\jpackage\*.exe'
deploy:
  description: Latest stable release
  provider: GitHub
  auth_token:
    secure: TjyyWBvqvk2/j05cBmpMpWsBslEdpJV2JOWy/5Uwr7IP1zKVMx/x97deqVskxx6L
  artifact: /.*file/
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
