---
image:
  - Ubuntu
  - macOS
  - Visual Studio 2019

for:
  - matrix:
      only:
        - image: Ubuntu
    install:
      - sudo apt-get -y update
      - sudo apt-get -y install rpm fakeroot

  - matrix:
      only:
        - image: Visual Studio 2019
    install:
      - cinst wixtoolset


  - matrix:
      only:
        - image: macOS
    install:
      - brew install adoptopenjdk



build_script:
  - ./gradlew --console=plain --info build
  - ./gradlew --console=plain dependencies --configuration=runtimeClasspath



artifacts:
  - name: debfile
    path: 'build\jpackage\*.deb'
  - name: rpmfile
    path: 'build\jpackage\*.rpm'
  - name: pkgfile
    path: 'build\jpackage\*.pkg'
  - name: dmgfile
    path: 'build\jpackage\*.dmg'
  - name: exefile
    path: 'build\jpackage\*.exe'
  - name: msifile
    path: 'build\jpackage\*.msi'

deploy:
  description: Latest stable release
  provider: GitHub
  auth_token:
    secure: TjyyWBvqvk2/j05cBmpMpWsBslEdpJV2JOWy/5Uwr7IP1zKVMx/x97deqVskxx6L
  artifact: /.*file/
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
