---
environment:
  JAVA_HOME: 'C:\Program Files\Java\jdk11'
build_script:
  - gradlew assemble
artifacts:
  - name: zipfile
    path: 'build\distributions\*.zip'
deploy:
  description: Latest stable release
  provider: GitHub
  auth_token:
    secure: TjyyWBvqvk2/j05cBmpMpWsBslEdpJV2JOWy/5Uwr7IP1zKVMx/x97deqVskxx6L
  artifact: zipfile
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
