---
image:
  - Ubuntu2004
  - Visual Studio 2019

stack: jdk 14

for:
  - matrix:
      only:
        - image: Ubuntu2004
    init:
      - sudo apt-get update
      - sudo apt-get install -y rpm fakeroot
    build_script:
      - ./gradlew --console=plain build

  - matrix:
      only:
        - image: Visual Studio 2019
    init:
      - choco install wixtoolset
    build_script:
      - gradlew build
      - dir build\jpackage



artifacts:
  - name: debfile
    path: 'build\jpackage\*.deb'
  - name: rpmfile
    path: 'build\jpackage\*.rpm'
  - name: pkgfile
    path: 'build\jpackage\*.pkg'
  - name: exefile
    path: 'build\jpackage\*.exe'

deploy:
  description: Latest stable release
  provider: GitHub
  auth_token:
    secure: TjyyWBvqvk2/j05cBmpMpWsBslEdpJV2JOWy/5Uwr7IP1zKVMx/x97deqVskxx6L
  artifact: /.*file/
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
