---
environment:
  JAVA_HOME: 'C:\Program Files\Java\jdk1.8.0'
build_script:
  - gradlew jfxNative
  - ls build\jfx\native
artifacts:
  - name: msifile
    path: 'build\jfx\native\*.msi'
  - name: exefile
    path: 'build\jfx\native\*.exe'
deploy:
  description: Latest stable release
  provider: GitHub
  auth_token:
    secure: TjyyWBvqvk2/j05cBmpMpWsBslEdpJV2JOWy/5Uwr7IP1zKVMx/x97deqVskxx6L
  artifact: msifile,exefile
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
