language: java

matrix:
  include:
    - os: linux
      jdk: openjdk8
      addons:
        apt:
          packages:
            - openjfx
            - rpm
            - fakeroot
    - os: osx
      osx_image: xcode9.3

script:
  - ./gradlew jfxNative
  - ls -l build/jfx/native

deploy:
  provider: releases
  api_key:
    secure: L6QTe4Jw5WyFmg9cVdBd24qVCzNGGbsM//M/xgFEcMyKb1iqq1OdEk3Z72Q3LLr6Us2GEaYkijK5Dydaa/ob9uVoMo+g2xVvOzvTb4vfb4WnJIU1wu6cSEUIib+sQvP/2kTlGf5bxOfpgUwQYowdsi04NbxhU5FJR0tPXKEOQR+La+Hpvwg+qfztGsZ0Badnd5bBydEYbWmSvDfRwdu4OeNr15dcvPCEMg1bQT0yNbgobLPs/GOfXHUvBfYqWwb/B7gxLBFVGWIsbxc0f0RbQmfQ4GXPSRG4o0spm8bMli2FOVLZdlRmeniGxryhFquKud59TzpYPaxAv5m676YQbuoISbElhw6BukcvGiTmi3STyKARCw0mcgbQws6z8Imt6UbSAHbv7kywuCwkisrOpbo2fTiZxk20yXptCNX4/tQDTZAHKNKKCI98qRcP4byI4WUbMPOjJIaEvM5hJqD+/+irI9v1JOJSEXNHGhXXFa9VRVDH6zrSww6dn/LWr9OQa2whIy8gRe27oOo2NCWUCrzDSeMdKbIB+r3eIdmPVLfmJHZYmEoPL/o3DnzZirQwx01QY9/S0qb7puieSjZhnXxJWaBwBHkjUCWmUEhMUaLYGrLvBvLc+2+Nn/T+yfYb1PXOAjYHbjlKs0YEfrtIoNZNStKxihnWYAScoxkfN6o=
  file_glob: true
  file:
    - 'build/jfx/native/*.deb'
    - 'build/jfx/native/*.rpm'
    - 'build/jfx/native/*.pkg'
  skip_cleanup: true
  on:
    tags: true
