plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
    id 'org.beryx.runtime' version '2.0.1'
    id 'com.coditory.manifest' version '1.1.0'
}

def versionMinor = '2.3'
version = "${versionMinor}.4".toString()

group = 'nu.mine.mosher.gedcom'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of 21
        vendor = JvmVendorSpec.ADOPTIUM
    }
}

repositories {
    mavenCentral()
    maven {
        url = uri('https://public:\u0067hp_fya6Kseu3XOBMg2icbg7f1LP6ZFYjj35v4Zj@maven.pkg.github.com/cmosher01/*')
    }
}

dependencies {
    implementation 'nu.mine.mosher.gedcom:gedcom-lib:latest.release', {
        exclude group: 'nu.mine.mosher.mopper', module: 'mopper'
    }
    implementation 'org.xerial:sqlite-jdbc:latest.release'
    implementation 'com.itextpdf:itext7-core:latest.release'

    implementation 'nu.mine.mosher.io:log-files:latest.release'

    implementation 'org.slf4j:jcl-over-slf4j:latest.release'
    implementation 'org.slf4j:log4j-over-slf4j:latest.release'
    implementation 'org.slf4j:jul-to-slf4j:latest.release'
    implementation 'org.slf4j:slf4j-api:latest.release'
    implementation 'ch.qos.logback:logback-classic:latest.release'

    testImplementation 'org.junit.jupiter:junit-jupiter:latest.release'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

application {
    mainClass = 'nu.mine.mosher.gedcom.xy.GenXyEditor'
}

javafx {
    version = 21
    modules = [
        'javafx.controls',
        'javafx.swing'
    ]
}

tasks.named('test', Test) {
    useJUnitPlatform()
    testLogging {
        events("skipped", "started", "passed", "failed")
    }
}

runtime {
    jpackage {
        appVersion = versionMinor
        def currentOs = org.gradle.internal.os.OperatingSystem.current()
        def imgType = currentOs.windows ? 'ico' : currentOs.macOsX ? 'icns' : 'png'
        imageOptions = ['--icon', "./src/main/resources/nu/mine/mosher/gedcom/xy/application.$imgType"]
    }
    modules = [
        'java.sql',
        'java.desktop',
        'java.logging',
        'java.prefs',
        'java.xml',
        'java.naming',
        'jdk.unsupported.desktop',
        'jdk.unsupported',
        'java.datatransfer'
    ]
}

assemble {
    dependsOn tasks.jpackage
}
